name: Build and publish nightly packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build-linux-binaries:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cross-build-binary
        with:
          target: ${{ matrix.target }}
          version: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
