name: Build and publish release packages

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux-binaries:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract asset version
        run: echo "ASSET_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - uses: ./.github/actions/cross-build-binary
        with:
          target: ${{ matrix.target }}
          version: ${{ env.ASSET_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
